#define WITH_D3D12_DEBUG_LAYER 1
#define WITH_D3D12_GPU_BASED_VALIDATION 0

#define GPU_ENABLE_VSYNC 1
#define GPU_MAX_BUFFERED_FRAMES 2
#define GPU_MAX_DESCRIPTORS (16 * 1024)
#define GPU_NUM_MSAA_SAMPLES 8
#define GPU_CLEAR_COLOR { 0.0f, 0.0f, 0.0f, 0.0f }
